### ISSUE TITLE
쿠기 및 star 글자사라짐

### ISSUE THREAD

**Issue by sungkuk5420** [rlarnfktkd1/sungkukJJang#1]
![image](https://user-images.githubusercontent.com/16679303/56259892-ba544780-610f-11e9-88b2-052ad3549d0b.png)

**Comment by sungkuk5420** [comment]
@rlarnfktkd1 이쪽 이슈도 클로우즈 해주세용!

**Comment by rlarnfktkd1** [comment]
감사합니다😆
